### ISSUE TITLE
can't launch the demo

### ISSUE THREAD

**Issue by wjxiz1992** [lizelu/SwiftDelegateDemo#1]
I use "git clone" with your repo site and I can't launch your demo. I don't know how to fix it . I am new to iOS dev. Thanks. 
here's the failure info:

<unknown>:0: error: no such file or directory: '/Users/wjxiz/Documents/developer/lizelu/SwiftDelegateDemo/SwiftDelegateDemo/BeautifulGrillCell.swift'
<unknown>:0: error: no such file or directory: '/Users/wjxiz/Documents/developer/lizelu/SwiftDelegateDemo/SwiftDelegateDemo/EditViewController.swift'
<unknown>:0: error: no such file or directory: '/Users/wjxiz/Documents/developer/lizelu/SwiftDelegateDemo/SwiftDelegateDemo/AppDelegate.swift'
<unknown>:0: error: no such file or directory: '/Users/wjxiz/Documents/developer/lizelu/SwiftDelegateDemo/SwiftDelegateDemo/ViewController.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by lizelu** [comment]
已更新代码，已解决上述问题~
